### ISSUE TITLE
"Expected all tensors to be on the same device"

### ISSUE THREAD

**Issue by MoonMoon82** [storyicon/comfyui_segment_anything#10]
Hi! After update to the latest version I get this error:

```
ERROR:root:Traceback (most recent call last):
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 305, in main
    (images, masks) = sam_segment(
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 229, in sam_segment
    masks, _, _ = predictor.predict_torch(
  File "e:\Stablediffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\sam_hq\predictor.py", line 114, in predict_torch
    sparse_embeddings, dense_embeddings = self.model.prompt_encoder(
  File "e:\Stablediffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "e:\Stablediffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\prompt_encoder.py", line 158, in forward
    box_embeddings = self._embed_boxes(boxes)
  File "e:\Stablediffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\prompt_encoder.py", line 97, in _embed_boxes
    corner_embedding = self.pe_layer.forward_with_coords(coords, self.input_image_size)
  File "e:\Stablediffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\prompt_encoder.py", line 214, in forward_with_coords
    return self._pe_encoding(coords.to(torch.float))  # B x N x C
  File "e:\Stablediffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\prompt_encoder.py", line 189, in _pe_encoding
    coords = coords @ self.positional_encoding_gaussian_matrix
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
```

Regardless which models I selected. What went wrong?

Kind regards

**Comment by ttulttul** [comment]
Make sure you are using SAMModelLoader (Segment Anything) rather than "SAM Model Loader". Doing so resolved this issue for me. Must be something about how the two model loaders deliver the model data.

**Comment by fly2outerspace** [comment]
![image](https://github.com/storyicon/comfyui_segment_anything/assets/157102924/19674e54-4510-4560-b0d9-f64a5f012494)
i am using this, it still have the error
 
![image](https://github.com/storyicon/comfyui_segment_anything/assets/157102924/013c0bb4-189e-4bfa-bf2a-0202a6598c92)

**Comment by alivelee** [comment]
if you use samload (impact), also change device_mode to prefer gpu can run it successfully 
![image](https://github.com/user-attachments/assets/3039b608-599c-4648-ae29-8e1c38f516bb)
