### ISSUE TITLE
ModuleNotFoundError: No module named 'timm'

### ISSUE THREAD

**Issue by chrisprojs** [storyicon/comfyui_segment_anything#23]
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\nodes.py", line 1798, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\comfyui_segment_anything\__init__.py", line 1, in <module>
    from .node import *
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 17, in <module>
    from sam_hq.build_sam_hq import sam_model_registry
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\comfyui_segment_anything\sam_hq\build_sam_hq.py", line 13, in <module>
    from .modeling.tiny_vit import TinyViT
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\comfyui_segment_anything\sam_hq\modeling\tiny_vit.py", line 15, in <module>
    from timm.models.layers import DropPath as TimmDropPath,\
ModuleNotFoundError: No module named 'timm'

Cannot import D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\comfyui_segment_anything module for custom nodes: No module named 'timm'

**Comment by storyicon** [comment]
Now dependencies will be installed automatically, and this issue should have been resolved. If you have any other problem, feel free to reopen the issue.

**Comment by geoff-m** [comment]
This still occurs.
