### ISSUE TITLE
ModuleNotFoundError: No module named 'segment_anything'

### ISSUE THREAD

**Issue by TFWol** [storyicon/comfyui_segment_anything#3]
I'm not having any luck getting this to load. Reinstalling didn't work either. It's the only extension I'm having issues with.

Traceback:
```shell
Traceback (most recent call last):
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\__init__.py", line 1, in <module>
    from .node import *
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 16, in <module>
    from sam_hq.predictor import SamPredictorHQ
  File "C:\Users\user\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\sam_hq\predictor.py", line 4, in <module>
    from segment_anything import SamPredictor
ModuleNotFoundError: No module named 'segment_anything'

Cannot import C:\Users\user\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything module for custom nodes: No module named 'segment_anything'
```

**Comment by Zdeto** [comment]
Same issue for me... :(
Don't know what to do.

```
File "e:\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\custom_nodes\comfyui_segment_anything\__init__.py", line 1, in <module>
    from .node import *
  File "E:\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 16, in <module>
    from sam_hq.predictor import SamPredictorHQ
  File "E:\ComfyUI\custom_nodes\comfyui_segment_anything\sam_hq\predictor.py", line 4, in <module>
    from segment_anything import SamPredictor
ModuleNotFoundError: No module named 'segment_anything'

Cannot import E:\ComfyUI\custom_nodes\comfyui_segment_anything module for custom nodes: No module named 'segment_anything'
```

**Comment by BlankFX1** [comment]
Same here.

```
Comfyroll Custom Nodes: Loaded
Traceback (most recent call last):
  File "B:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "B:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\__init__.py", line 1, in <module>
    from .node import *
  File "B:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 16, in <module>
    from sam_hq.predictor import SamPredictorHQ
  File "B:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\sam_hq\predictor.py", line 4, in <module>
    from segment_anything import SamPredictor
ModuleNotFoundError: No module named 'segment_anything'

Cannot import B:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything module for custom nodes: No module named 'segment_anything'

Import times for custom nodes:
[...]
   0.0 seconds (IMPORT FAILED): B:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
```

**Comment by pluberd** [comment]
`pip install segment_anything`

(linux)

**Comment by BlankFX1** [comment]
> `pip install segment_anything`
> 
> (linux)

Won't work out of the box
(windows)

Not even when "activating" python_embeded (embedded?) as a venv and using this command. It will just give error:
```
(venv) B:\ComfyUI_windows_portable\python_embeded>pip install segment_anything
Fatal error in launcher: unable to create process with '"D:\a\ComfyUI\python_embeded\python.exe" "B:\ComfyUI_windows_portable\python_embeded\Scripts\pip.exe" install segment_anything': the system cannot find the specified file.
```

As I don't even have this mentioned Drive "D:\", I assume it's related to something hardcoded.

Until this gets fixed, I tried it the dirty way and simply made a copy of the folders
`segment_anything`
and
`segment_anything-1.0.dist-info`
from an A1111-venv and moved it to
`ComfyUI_windows_portable\python_embeded\Lib\site-packages`

which allowed ComfyUI to boot up - at least for the moment.

**Comment by TFWol** [comment]
Glad I'm not the only one with this problem

> > `pip install segment_anything`
> > (linux)
> 
> Won't work out of the box (windows)
> 
> Not even when "activating" python_embeded (embedded?) as a venv and using this command. It will just give error:
> 
> ```
> (venv) B:\ComfyUI_windows_portable\python_embeded>pip install segment_anything
> Fatal error in launcher: unable to create process with '"D:\a\ComfyUI\python_embeded\python.exe" "B:\ComfyUI_windows_portable\python_embeded\Scripts\pip.exe" install segment_anything': the system cannot find the specified file.
> ```
> 
> As I don't even have this mentioned Drive "D:", I assume it's related to something hardcoded.
> 
> Until this gets fixed, I tried it the dirty way and simply made a copy of the folders `segment_anything` and `segment_anything-1.0.dist-info` from an A1111-venv and moved it to `ComfyUI_windows_portable\python_embeded\Lib\site-packages`
> 
> which allowed ComfyUI to boot up - at least for the moment.

Nice, thanks for sharing. I'll have to try that out once I'm able to.

**Comment by TFWol** [comment]
I was able to get it working with this command (put in the path to wherever your python_embeded is)
```shell
"..\..\python_embeded\python.exe" -s -m pip install segment-anything
```

**Comment by Manish-cel** [comment]
> I was able to get it working with this command
> 
> ```shell
> "ComfyUI_windows_portable\python_embeded\python.exe" -s -m pip install segment-anything
> ```

@TFWol  where to put this command?
i am new to this, need help.

**Comment by TFWol** [comment]
@Manish-cel Not sure what to clarify, you would open a command prompt and replace `"ComfyUI_windows_portable\python_embeded\python.exe"` with the full path to your portable ComfyUI.

**Comment by storyicon** [comment]
Now dependencies will be installed automatically, and this issue should have been resolved. If you have any other problem, feel free to reopen the issue.

**Comment by lindongyue7** [comment]
ModuleNotFoundError: No module named 'segment_anything'

2024-09-04 16:34:49,544- root:2013- WARNING- Cannot import D:\comfyui\ComfyUI\custom_nodes\comfyui_segment_anything-main module for custom nodes: No module named 'segment_anything'
PS D:\comfyui\ComfyUI> pip show segment_anything
Name: segment_anything
Version: 1.0
Summary:
Home-page:
Author:
Author-email:
License:
Location: C:\Users\PC\miniconda3\Lib\site-packages
Editable project location: D:\comfyui\ComfyUI\custom_nodes\segment-anything-main
Requires:
Required-by:
