### ISSUE TITLE
Cannot import /root/ComfyUI/custom_nodes/comfyui_segment_anything module for custom nodes: A Message class can only inherit from Message

### ISSUE THREAD

**Issue by shawpook** [storyicon/comfyui_segment_anything#32]
Traceback (most recent call last):
  File "/root/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/comfyui_segment_anything/__init__.py", line 1, in <module>
    from .node import *
  File "/root/ComfyUI/custom_nodes/comfyui_segment_anything/node.py", line 17, in <module>
    from sam_hq.build_sam_hq import sam_model_registry
  File "/root/ComfyUI/custom_nodes/comfyui_segment_anything/sam_hq/build_sam_hq.py", line 13, in <module>
    from .modeling.tiny_vit import TinyViT
  File "/root/ComfyUI/custom_nodes/comfyui_segment_anything/sam_hq/modeling/tiny_vit.py", line 15, in <module>
    from timm.models.layers import DropPath as TimmDropPath,\
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/__init__.py", line 3, in <module>
    from .models import create_model, list_models, list_pretrained, is_model, list_modules, model_entrypoint, \
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/models/__init__.py", line 1, in <module>
    from .beit import *
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/models/beit.py", line 49, in <module>
    from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/data/__init__.py", line 5, in <module>
    from .dataset import ImageDataset, IterableImageDataset, AugMixDataset
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/data/dataset.py", line 13, in <module>
    from .readers import create_reader
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/data/readers/__init__.py", line 1, in <module>
    from .reader_factory import create_reader
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/data/readers/reader_factory.py", line 3, in <module>
    from .reader_image_folder import ReaderImageFolder
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/data/readers/reader_image_folder.py", line 11, in <module>
    from timm.utils.misc import natural_key
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/utils/__init__.py", line 15, in <module>
    from .summary import update_summary, get_outdir
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/timm/utils/summary.py", line 9, in <module>
    import wandb
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/sdk/__init__.py", line 4, in <module>
    from .artifacts.artifact import Artifact  # noqa: F401
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 36, in <module>
    from wandb.apis.normalize import normalize_exceptions
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/apis/__init__.py", line 43, in <module>
    from .internal import Api as InternalApi  # noqa
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/apis/internal.py", line 3, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 48, in <module>
    from ..lib import retry
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 10, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/proto/wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/wandb/proto/v3/wandb_internal_pb2.py", line 15, in <module>
    from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/google/protobuf/timestamp_pb2.py", line 19, in <module>
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.timestamp_pb2', globals())
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/google/protobuf/internal/builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/google/protobuf/internal/builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
TypeError: A Message class can only inherit from Message

Cannot import /root/ComfyUI/custom_nodes/comfyui_segment_anything module for custom nodes: A Message class can only inherit from Message
Searge-SDXL v4.0 in /root/ComfyUI/custom_nodes/SeargeSDXL

Other nodes have also reported this issue, but no solution has been found

**Comment by storyicon** [comment]
I have encountered similar problems before, which may solve your problem: https://github.com/ssitu/ComfyUI_roop/issues/1#issuecomment-1776996053

**Comment by shawpook** [comment]
> 我以前遇到过类似的问题，可能会解决你的问题：[ssitu/ComfyUI_roop#1（评论）](https://github.com/ssitu/ComfyUI_roop/issues/1#issuecomment-1776996053)
> 
> @shawpook

Success, thank you！

**Comment by storyicon** [comment]
I'm glad to hear that. If you have any other questions, feel free to raise new issues.
