### ISSUE TITLE
Getting a "Ran out of input" error from one of the dependencies when comfyui starts with segment anything

### ISSUE THREAD

**Issue by waywardspooky** [storyicon/comfyui_segment_anything#47]
OS Linux Mint 21.2 x86_64, Kernel: 5.15.0-92-generic. Python version 3.10, latest comfyui

Traceback (most recent call last):
  File "/opt/LLM/jttw/components/comfyui/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/LLM/jttw/components/comfyui/custom_nodes/comfyui_segment_anything/__init__.py", line 1, in <module>
    from .node import *
  File "/opt/LLM/jttw/components/comfyui/custom_nodes/comfyui_segment_anything/node.py", line 19, in <module>
    from local_groundingdino.util.utils import clean_state_dict as local_groundingdino_clean_state_dict
  File "/opt/LLM/jttw/components/comfyui/custom_nodes/comfyui_segment_anything/local_groundingdino/util/utils.py", line 12, in <module>
    from local_groundingdino.util.slconfig import SLConfig
  File "/opt/LLM/jttw/components/comfyui/custom_nodes/comfyui_segment_anything/local_groundingdino/util/slconfig.py", line 14, in <module>
    from yapf.yapflib.yapf_api import FormatCode
  File "/opt/LLM/jttw/components/comfyui/comfyui_venv/lib/python3.10/site-packages/yapf/__init__.py", line 41, in <module>
    from yapf.yapflib import yapf_api
  File "/opt/LLM/jttw/components/comfyui/comfyui_venv/lib/python3.10/site-packages/yapf/yapflib/yapf_api.py", line 38, in <module>
    from yapf.pyparser import pyparser
  File "/opt/LLM/jttw/components/comfyui/comfyui_venv/lib/python3.10/site-packages/yapf/pyparser/pyparser.py", line 44, in <module>
    from yapf.yapflib import format_token
  File "/opt/LLM/jttw/components/comfyui/comfyui_venv/lib/python3.10/site-packages/yapf/yapflib/format_token.py", line 23, in <module>
    from yapf.pytree import pytree_utils
  File "/opt/LLM/jttw/components/comfyui/comfyui_venv/lib/python3.10/site-packages/yapf/pytree/pytree_utils.py", line 30, in <module>
    from yapf_third_party._ylib2to3 import pygram
  File "/opt/LLM/jttw/components/comfyui/comfyui_venv/lib/python3.10/site-packages/yapf_third_party/_ylib2to3/pygram.py", line 29, in <module>
    python_grammar = driver.load_grammar(_GRAMMAR_FILE)
  File "/opt/LLM/jttw/components/comfyui/comfyui_venv/lib/python3.10/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 252, in load_grammar
    g.load(gp)
  File "/opt/LLM/jttw/components/comfyui/comfyui_venv/lib/python3.10/site-packages/yapf_third_party/_ylib2to3/pgen2/grammar.py", line 96, in load
    d = pickle.load(f)
EOFError: Ran out of input

**Comment by DJMeng** [comment]
Did you solve it?

**Comment by DJMeng** [comment]
> Did you solve it?

pip uninstall yapf

pip install yapf

it is ok！
