### ISSUE TITLE
GroundingDinoModelLoader (segment anything) Node Does Not Exist

### ISSUE THREAD

**Issue by octadion** [storyicon/comfyui_segment_anything#90]
I am building ComfyUI based on the (https://github.com/fofr/cog-comfyui) repository. I have added comfyui_segment_anything to the custom nodes directory, but I am encountering the following error when running the workflow:

```
Running workflow
[ComfyUI] got prompt
[ComfyUI] invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node GroundingDinoModelLoader (segment anything) does not exist.', 'details': "Node ID '#23'", 'extra_info': {}}
ComfyUI error: 400 Bad Request
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 352, in _predict
    result = predict(**payload)
  File "/src/predict.py", line 137, in predict
    self.comfyUI.run_workflow(wf)
  File "/src/comfyui.py", line 271, in run_workflow
    prompt_id = self.queue_prompt(workflow)
  File "/src/comfyui.py", line 202, in queue_prompt
    raise Exception(
Exception: ComfyUI Error – Your workflow could not be run. This usually happens if you’re trying to use an unsupported node. Check the logs for 'KeyError:' details, and go to https://github.com/fofr/cog-comfyui to see the list of supported custom nodes.
```

**Comment by pierbdt** [comment]
how did you fix it?
